export const CROSSWORD_PUZZLES = [
  {
    size: 9,
    blocks: [
      [1, 8],
      [2, 6],
      [2, 7],
      [3, 1],
      [3, 3],
      [4, 1],
      [4, 3],
      [4, 4],
      [4, 6],
      [4, 7],
      [5, 1],
      [5, 3],
      [5, 4],
      [5, 6],
      [5, 7],
      [6, 3],
      [6, 4],
      [6, 6],
      [6, 7],
      [7, 2],
      [7, 3],
      [7, 4],
      [7, 6],
      [7, 7],
      [8, 6],
      [8, 7],
      [8, 8],
    ],
    entries: [
      { number: 1, direction: "across", row: 0, col: 0, answer: "breakbulk", clue: "Non-containerized, individual, or unitized freight" },
      { number: 1, direction: "down", row: 0, col: 0, answer: "backhaul", clue: "A return journey taken by a transport vehicle heading back toward its point of origin" },
      { number: 2, direction: "across", row: 1, col: 1, answer: "stowage", clue: "The precise spatial planning and physical securing of cargo on board a vessel" },
      { number: 3, direction: "down", row: 1, col: 2, answer: "tariff", clue: "A scheduled duty or tax imposed by a national government on imports or exports" },
      { number: 4, direction: "across", row: 2, col: 1, answer: "yard", clue: "Where freight cars get sorted and stored" },
      { number: 5, direction: "down", row: 2, col: 5, answer: "harmony", clue: "A noun that means agreement, peaceful living, or a pleasing combination of different musical notes" },
      { number: 6, direction: "down", row: 2, col: 8, answer: "bonded", clue: "A controlled facility or warehouse status" },
      { number: 7, direction: "across", row: 3, col: 4, answer: "cargo", clue: "The goods or merchandise carried by a ship, airplane, train, or truck" },
      { number: 8, direction: "down", row: 6, col: 1, answer: "idl", clue: "International Developing Logistics" },
      { number: 9, direction: "across", row: 8, col: 0, answer: "fleet", clue: "A company's whole lineup of trucks or vans" },
    ],
  },
];
