export const CROSSWORD_PUZZLES = [
  {
    size: 9,
    blocks: [
      [1, 8],
      [2, 2],
      [2, 4],
      [2, 5],
      [2, 6],
      [4, 2],
      [4, 4],
      [4, 5],
      [4, 6],
      [5, 2],
      [6, 2],
      [6, 4],
      [6, 5],
      [6, 6],
      [6, 7],
      [7, 2],
      [7, 4],
      [7, 5],
      [7, 6],
      [7, 7],
      [8, 0],
      [8, 7],
    ],
    entries: [
      { number: 1, direction: "across", row: 0, col: 0, answer: "breakbulk", clue: "Non-containerized, individual, or unitized freight" },
      { number: 1, direction: "down", row: 0, col: 0, answer: "backhaul", clue: "A return journey taken by a transport vehicle heading back toward its point of origin" },
      { number: 2, direction: "across", row: 1, col: 1, answer: "harmony", clue: "A noun that means agreement, peaceful living, or a pleasing combination of different musical notes" },
      { number: 3, direction: "down", row: 1, col: 7, answer: "yard", clue: "Where freight cars get sorted and stored" },
      { number: 4, direction: "down", row: 2, col: 1, answer: "freight", clue: "Goods or products moved in large amounts by ship, train, truck, or airplane" },
      { number: 5, direction: "down", row: 2, col: 3, answer: "carrier", clue: "Transportation company contracted to move freight from origin to destination" },
      { number: 6, direction: "down", row: 2, col: 8, answer: "racking", clue: "Industrial vertical shelving system used for high-density storage" },
      { number: 7, direction: "across", row: 3, col: 2, answer: "cargo", clue: "The goods or merchandise carried by a ship, airplane, train, or truck" },
      { number: 8, direction: "across", row: 5, col: 4, answer: "truck", clue: "A large motor vehicle designed to transport goods, carry heavy loads, or perform specialized work" },
      { number: 9, direction: "across", row: 8, col: 1, answer: "tariff", clue: "A scheduled duty or tax imposed by a national government on imports or exports" },
    ],
  },
];
