export const AVAILABLE_VEHICLES = [
  {
    name: "Mitsubishi Canter (G 97603)",
    subtitle: "White/Blue",
    image: "/vehicles/pickup-truck.svg",
    category: "Pick-up - 3 Ton",
  },
  {
    name: "Volvo FH 460 (X 87086)",
    subtitle: "Red/White",
    image: "/vehicles/semi-truck.svg",
    category: "Unit",
  },
  {
    name: "Mitsubishi Canter (U 43559)",
    subtitle: "White",
    image: "/vehicles/pickup-truck.svg",
    category: "Pick-up - 3 Ton",
  },
  {
    name: "Volkswagen Caddy (Z 76009)",
    subtitle: "White",
    image: "/vehicles/van.svg",
    category: "Van - 1 Ton",
  },
  {
    name: "Volvo FH (Z 89256)",
    subtitle: "White",
    image: "/vehicles/semi-truck.svg",
    category: "Unit",
  },
  {
    name: "Toyota Lite Ace (Z 85021)",
    subtitle: "White",
    image: "/vehicles/van.svg",
    category: "Van - 1 Ton",
  },
  {
    name: "Nissan Urvan (E 66754)",
    subtitle: "White",
    image: "/vehicles/van.svg",
    category: "Van - 3 Ton",
  },
  {
    name: "Mitsubishi Canter (H 78596)",
    subtitle: "White",
    image: "/vehicles/pickup-truck.svg",
    category: "Pick-up - 3 Ton",
  },
  {
    name: "Nissan Urvan (Y 48580)",
    subtitle: "White",
    image: "/vehicles/van.svg",
    category: "Van - 1 Ton",
  },
  {
    name: "Toyota Hiace (Q 55372)",
    subtitle: "White",
    image: "/vehicles/van.svg",
    category: "Van - 1 Ton",
  },
  {
    name: "Volvo FH (W 31408)",
    subtitle: "White",
    image: "/vehicles/semi-truck.svg",
    category: "Unit",
  },
  {
    name: "Volvo FH (B 52480)",
    subtitle: "White/Red/Blue",
    image: "/vehicles/semi-truck.svg",
    category: "20ft Container Truck",
  },
  {
    name: "Volvo FMX330 (P 65166)",
    subtitle: "White",
    image: "/vehicles/semi-truck.svg",
    category: "20ft Container Truck",
  },
  {
    name: "Toyota Hiace (DD 44158)",
    subtitle: "White",
    image: "/vehicles/van.svg",
    category: "Van - 1 Ton",
  },
  {
    name: "Nissan Urvan (DD 46268)",
    subtitle: "White",
    image: "/vehicles/van.svg",
    category: "Van - 1 Ton",
  },
  {
    name: "Nissan Urvan (DD 21814)",
    subtitle: "White",
    image: "/vehicles/van.svg",
    category: "Van - 1 Ton",
  },
];
